# Site settings
title: Michael
description: "Press [Spacebar]"
baseurl: '' # for test: remove string '/space-jekyll-templa' to ''
url: "http://michael.humanfactors.io" 
# User settings
username: Michael Wilson
user_title: Open Source Mike
email: michael@humanfactors.io
twitter_username: humanfactorsio
github_username:  humanfactors
profile_picture: http://www.humanfactors.io/user/pages/01.about/avatar.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: posts/
  - title: tutorials
    url: tutorials/
  - title: tags
    url: tags/
  - title: about me
    url: about/
# projects in header index
projects:
  - name: Interruptions in Air Traffic Control
    url: http://journals.sagepub.com/doi/abs/10.1177/1541931213601055
  - name: Skanky Dotfiles
    url: https://github.com/humanfactors/skanky-config.git
  - name: Learning Spacemacs
    url: https://github.com/humanfactors/spacemacs 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
